In [1]:
import numpy as np

***Relu - Rectified Linear Unit(Hidden Layer)***

In [2]:
def relu(x):
    return np.maximum(0,x)

In [3]:
relu(10)

10

In [4]:
relu(-5)

0

In [5]:
relu(np.array([-1,0,1,2]))

array([0, 0, 1, 2])

***Leaky ReLU(Hidden Layer)***

In [6]:
def leaky_relu(x, alpha = 0.01):
    return np.where(x>0, x , x*alpha)

In [7]:
leaky_relu(5)

array(5.)

In [8]:
leaky_relu(-5)

array(-0.05)

***ELU - Exponential Linear Unit(Hidden Layer)***

In [9]:
def elu(x, alpha = 1.0):
    return np.where(x > 0 , x , alpha * (np.exp(x)-1))

In [10]:
elu(5)

array(5.)

In [11]:
elu(-5)

array(-0.99326205)

In [12]:
elu(np.array([-1,0,1,2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

***Sigmoid(output layer & Binaryclass Problem)***

In [13]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [14]:
sigmoid(-5)

0.0066928509242848554

In [15]:
sigmoid(5)

0.9933071490757153

In [16]:
sigmoid(np.array([-1,0,1,2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

***Softmax(Output Layer & Multiclass Problem)***

In [17]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [18]:
probability = softmax(np.array([2,1,0.5]))

In [19]:
probability

array([0.62853172, 0.2312239 , 0.14024438])

In [20]:
sum(probability)

1.0

***Swish(Hidden Layer)***

In [21]:
def swish(x, beta =1.0 ):
    return x * sigmoid(beta*x)

In [22]:
swish(5)

4.966535745378576

In [23]:
swish(np.array([-1,0,1,2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

*** Linear (Output Layer)***

In [24]:
def linear(x):
    return x

In [25]:
linear(5)

5

In [26]:
linear(-5)

-5

***Tanh (Hyperbolic Tangent)***

In [27]:
def tanh(x):
    return np.tanh(x)

In [28]:
tanh(-5)

-0.9999092042625951

In [29]:
tanh(5)

0.9999092042625951

In [30]:
tanh(np.array([-1,0,1,2]))

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [31]:
#another way
import math

In [32]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [33]:
tanh(-5)

-0.999909204262595

In [34]:
tanh(5)

0.999909204262595

In [36]:
tanh(np.array([-1,0,1,2]))

TypeError: only length-1 arrays can be converted to Python scalars